name: Generate_Hash
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
      - name: Calculate sha256sum of folders containing .ows files
        run: |
          docker pull biodepot/launcher-utils:latest
          find . -type f -name '*.ows' -printf '%h\n' | LC_ALL=C sort -u --ignore-case | while read -r dir; do hash=$(docker run -v ".":"/workspace/mnt" biodepot/launcher-utils:latest "hash" /workspace/mnt/$dir); echo "$hash"; done > hash.txt
      - name: Add hash to workflows.json
        run: |
          cat hash.txt | while read -r line; do
            hash="$(echo $line | awk '{print $1}')"
            workflow="$(echo $line | awk '{print $2}')"
            workflow_index="$(cat workflows.json | jq '[.workflows[].location]|index("'$workflow'")')"
            workflow_at_index="$(cat workflows.json | jq 'del(.workflows['$workflow_index'].checksum)' | jq '.workflows['$workflow_index'] += {"checksum": "'$hash'"}')"
            echo $workflow_at_index | jq "." > workflows.json
          done
          cat workflows.json
